### xxl-job, datasource
spring.datasource.url=${FIREFOX_SPRING_DATASOURCE_URL:}
spring.datasource.username=${FIREFOX_SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${FIREFOX_SPRING_DATASOURCE_PASSWORD:}

### xxl-job email
spring.mail.host=smtp.qq.com
spring.mail.port=25
spring.mail.username=${FIREFOX_SPRING_MAIL_USERNAME:}
spring.mail.password=${FIREFOX_SPRING_MAIL_PASSWORD:}

### xxl-job login
xxl.job.login.username=${FIREFOX_XXL_JOB_LOGIN_USERNAME:}
xxl.job.login.password=${FIREFOX_XXL_JOB_LOGIN_PASSWORD:}
