# nacos配置
nacos.server-addr=${FIREFOX_NACOS_SERVER_ADDR:}
nacos.namespace=d6c00be1-e615-4b82-af3a-1abd5d4cf2ea
nacos.group=firefox-cloud
nacos.username=${FIREFOX_NACOS_USERNAME:}
nacos.password=${FIREFOX_NACOS_PASSWORD:}
nacos.yml.group=DEFAULT_GROUP

# 日志存储路径
logging.file.path=/data/projects/logs
