# nacos配置
nacos.server-addr=${FIREFOX_NACOS_SERVER_ADDR:}
nacos.namespace=b8c05865-7bbd-476a-be3d-cc4a0eff8faf
nacos.group=open
nacos.username=${FIREFOX_NACOS_USERNAME:}
nacos.password=${FIREFOX_NACOS_PASSWORD:}
nacos.yml.group=DEFAULT_GROUP

# 日志存储路径
logging.file.path=/data/projects/logs
