########################## 统一变量配置 ##########################

##### 数据库配置
firefox.datasource.ip=${FIREFOX_FIREFOX_DATASOURCE_IP:}
firefox.datasource.port=3307
firefox.datasource.username=${FIREFOX_FIREFOX_DATASOURCE_USERNAME:}
firefox.datasource.password=${FIREFOX_FIREFOX_DATASOURCE_PASSWORD:}

##### redis配置
firefox.redis.ip=${FIREFOX_FIREFOX_REDIS_IP:}
firefox.redis.port=6079
firefox.redis.password=${FIREFOX_FIREFOX_REDIS_PASSWORD:}
firefox.redis.database=0
firefox.redis.database-sys=1
firefox.redis.timeout=5000